name: Generate Documentation PR

on:
  pull_request:
    # Run when commits are pushed to a PR or the PR is opened/reopened
    types: [synchronize, opened, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  gen-docs:
    # Exclude PRs that already carry any docs-related label (e.g. 'docs' or 'docs:auto')
    if: ${{ !contains(join(github.event.pull_request.labels.*.name, ','), 'docs') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; else pip install PyGithub requests jsonschema; fi

      - name: Run docs generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PLAN_MODEL: gpt-4o-mini
        run: |
          python scripts/generate_docs.py
