name: Generate Docs Dry-Run

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  gen-docs-dryrun:
    name: docs dry-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; fi

      - name: Run docs generator (dry-run)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/generate_docs.py --dry-run
      - name: Upload dry-run artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs-dryrun
          path: tmp/docs-dryrun
          if-no-files-found: ignore
