name: AI Plan Issues

on:
  issue_comment:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  plan:
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.comment.body, '/plan') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Generate plan from issue
        env:
          GITHUB_TOKEN: ${{ secrets.POP_FLY_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -u scripts/ai_plan_issue.py
