name: Scaffold from Plan

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      issue: { description: 'Issue number', required: false }

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  scaffold:
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.comment.body, '/scaffold') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Scaffold branch and PR
        env:
          GITHUB_TOKEN: ${{ secrets.POP_FLY_PAT }}
        run: |
          python -u scripts/scaffold_from_plan.py
