name: Scaffold from Plan

on:
  push:
    branches:
      - 'feature/plan-**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'The feature branch with a plan to scaffold from'
        required: true

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Scaffold branch and PR
        env:
          GITHUB_TOKEN: ${{ secrets.POP_FLY_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # The script will need to know which branch it's on
          BRANCH_NAME: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref_name }}
        run: |
          pip install PyGithub requests
          python -u scripts/scaffold_from_plan.py --branch "$BRANCH_NAME"

