name: Update PR Checklist

on:
  pull_request:
    types: [opened, edited, synchronize]
  workflow_dispatch:
    inputs:
      pr: { description: 'PR number', required: false }

permissions:
  contents: read
  pull-requests: write
  issues: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Sync checklist in PR body
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          python -u scripts/update_pr_checklist.py
